version: '3'

services:
  jaeger-agent:
    build: jaeger-agent
    environment:
      # more options: https://www.jaegertracing.io/docs/1.11/deployment/#all-options-1
      REPORTER_TYPE: grpc
      REPORTER_GRPC_HOST_PORT: jaeger-collector:14250
      PROCESSOR_JAEGER_BINARY_SERVER_HOST_PORT: :6832
    command: wait.sh http://jaeger-collector:14269 5 20 "jaeger-agent"
    ports:
      - "6832:6832" # receiving traces via UDP
      - "5778:5778" # get sampling strategies
    networks:
      - aparnet
    depends_on:
      - jaeger-collector

  jaeger-collector:
    build: jaeger-collector
    environment:
      # more options: https://www.jaegertracing.io/docs/1.11/deployment/#all-options-1
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
    restart: on-failure
    # todo: eliminate duplication of health-check url in 'command'
    command: wait.sh http://elasticsearch:9200 5 20 "jaeger-collector"
    ports:
      - "14269:14269" # healthcheck
      - "14250:14250" # for receiving spans via grpc
    networks:
      - aparnet
    depends_on:
      - elasticsearch

  jaeger-query:
    build: jaeger-query
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
    ports:
      - "16686:16686" # provides UI
      - "16687:16687" # healthcheck
    networks:
      - aparnet
    command: wait.sh http://elasticsearch:9200 5 20 "jaeger-query"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:5.6-alpine
    ports:
      - "9200:9200" # server listens here
      - "9300:9300"
    networks:
      - aparnet

networks:
  aparnet: